### ISSUE TITLE
Concurrent writes to cache with same session Id but different data key result in data loss

### ISSUE THREAD

**Issue by RobTaylor76** [hmrc/mongo-caching#5]
We have an issue when we have multiple concurrent http requests for the same session. Each request tries to store data in the key store/mongo cache. Each request uses a different data key to store it's data. 

i.e here are 2 of our request urls...

http://localhost:8400/keystore/EI/703497ac-272b-4f8b-87d7-9440c44b7b2c/data/040320150441451ceab688f431499798a0763271465c5e

http://localhost:8400/keystore/EI/703497ac-272b-4f8b-87d7-9440c44b7b2c/data/040320150441453067fc1953154d2798fe25dbf286ba51

session = 703497ac-272b-4f8b-87d7-9440c44b7b2c
cache keys =  040320150441451ceab688f431499798a0763271465c5e / 040320150441453067fc1953154d2798fe25dbf286ba51

If the requests are sequential all is fine. However once they occur concurrently there is data loss. 

The results are non deterministic. 

A quick look at the code seems to suggest that the cache data is read/updated in memory and re-written to the database.

  protected def transformData(key: String, value: JsValue) = data match {
    case Some(js: JsValue) => findAndReplaceTransformer(js, key, value)
    case _ =>
      Logger.info(s"The cached entity with id '${id.id}' contained no data. This should not be possible.")
      throw new InvalidStateException(s"The cached entity with id '${id.id}' contained no data")
  }

  private [model] def findAndReplaceTransformer(toTransform: JsValue, key: String, value: JsValue) = {
    toTransform.transform {
      (__ \ key).json.prune andThen __.json.update(__.read[JsObject].map {
        o => o ++ JsObject(Seq(key -> value))
      })
    } fold(
      errors => throw new Exception("Failed to update the defined path" + errors), //FIXME: is throwing an exception correct?
      success => Some(success)
      )
  }

however with concurrent requests, the same thing is done by multiple threads and the last one to save to the database wins. 

We can reproduce this problem repeatedly.

As key store is ultimately just a wrapper for mongo-caching i am raising the issue here.

@duncancrawford

**Comment by duncancrawford** [comment]
Please add the test that proves this issue. This said I think this has been identified as an known issue.

**Comment by pacenick** [comment]
Please note, the atomic release of mongo-caching will resolve this issue. Today mongo-caching will first read the record and then apply the requested update. With atomics, the record is no longer read!
